### ISSUE TITLE
Generated name and exported type

### ISSUE THREAD

**Issue by gonghaokaka** [runtime-env/runtime-env#150]
First of all, thank you for creating this repo! It is a really helpful tool for injecting environment variables at runtime. I have a clarification that I hope you can help us with.

**Context:**

There is no named and exported type for runtimeEnv generated by `dotenv -e .env -- runtime-env gen-ts --output-file-path runtime-env.d.ts`. Every time we have a new variable, we need to manually update the type in the projectEnv.ts file.

```
--runtime-env.d.ts

declare const runtimeEnv: DeepReadonly<{
  APP_DETAILS: string;
  WEB_DETAILS: string;
}>
```

```
--projectEnv.ts
declare global {
  var runtimeEnv: Readonly<{
    APP_DETAILS: string;
    WEB_DETAILS: string;
    // need to manually add new types from here
  }>;
}

const env = {
  ...runtimeEnv,
  ...others,
};

export { env }
```

It would be nice if generated type can be named and exported, so our projectEnv.ts can remain unchanged

```
--runtime-env.d.ts

export type RuntimeEnv = DeepReadonly<{
  APP_DETAILS: string;
  WEB_DETAILS: string;
}>;

declare const runtimeEnv: RuntimeEnv;
```

```
--projectEnv.ts
declare global {
  var runtimeEnv: RuntimeEnv;
}

const env = {
  ...runtimeEnv,
  ...others,
};

export { env }
```

Hope it makes sense. Thanks!

**Comment by soc221b** [comment]
You could do this to obtain the typeof `runtimeEnv` as well:

```ts
type RuntimeEnv = typeof runtimeEnv
```

**Comment by gonghaokaka** [comment]
@soc221b the generated `runtimeEnv` const is not exported typescript would not like it. 

```
import { runtimeEnv } from '../runtime-env.js';  <- typescript error here

type RuntimeEnv = typeof runtimeEnv;
```

or we can do something like 
```
export declare const runtimeEnv: DeepReadonly<{
  APP_DETAILS: string;
  WEB_DETAILS: string;
}>;
```

**Comment by soc221b** [comment]
The `runtimeEnv` is declared as global variable, we can simply do typeof it without `import`:

```diff
- import { runtimeEnv } from '../runtime-env.js';  <- typescript error here

type RuntimeEnv = typeof runtimeEnv;
```

**Comment by soc221b** [comment]
I realized that I didn't properly augment the global variable runtimeEnv. In this patch, I also exported the `RuntimeEnv` type. As of v0.5.2, you can import it from runtime-env.d.ts like this:

```ts
import type { RuntimeEnv } from 'path/to/runtime-env.d.ts`
```

Thank you~
