### ISSUE TITLE
[Question] How to use `runtime-env` in a local development setup

### ISSUE THREAD

**Issue by dmohns** [runtime-env/runtime-env#252]
Hey 👋 

First of all, thanks for these amazing libraries 🙏 

In a project where I need to use environment variables I'm trying to decide between `runtime-env` and `import-meta-env`.

What isn't fully clear to me, is, how we are intended to use `runtime-env` in a local development setup. For `import-meta-env` this is clear by using the corresponding plugin and compile-time interpolation.

Is it correct to assume that `runtime-env` is also intended to be used for local development setups?

Thanks

**Comment by soc221b** [comment]
Hi👋

This package aims to provide a set of code generator, and let users choose _when_ to generate/interpolate corresponding js/ts/html based on your use case/scenario.

There is a development example (webpack dev-server) in the example directory. It uses the watch mode, but you could also simply run those generators on the package's lifecycle script: `prepare` if you don't need it.

Hope this helps. 😀

**Comment by dmohns** [comment]
Alright, the example is indeed very helpful 🙏 

I think my confusion was, that I was thinking "compile-time" vs "run-time" are equivalent to interpolation vs generate-js. But that's actually not true, as they are different things. In `runtime-env` this distinction becomes more clear, as it's user's responsibility and to choose _when_ and _how_.

Thanks for the clarification!
